# Generated by Django 5.1.2 on 2024-10-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectroTrail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible')], max_length=20)),
            ],
        ),
    ]
