# Generated by Django 5.1.2 on 2024-10-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectroTrail', '0002_evmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='evmodel',
            name='name',
            field=models.CharField(default='name', max_length=20),
        ),
    ]
