# Generated by Django 5.1.2 on 2024-10-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectroTrail', '0003_evmodel_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evmodel',
        ),
        migrations.AddField(
            model_name='evreview',
            name='name',
            field=models.CharField(default='name', max_length=20),
        ),
        migrations.AddField(
            model_name='evreview',
            name='type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible')], default='select', max_length=20),
        ),
    ]
