# Generated by Django 5.1.2 on 2024-10-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectroTrail', '0004_delete_evmodel_evreview_name_evreview_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='evreview',
            name='name',
        ),
        migrations.RemoveField(
            model_name='evreview',
            name='type',
        ),
    ]
