# Generated by Django 5.1.2 on 2024-10-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectroTrail', '0005_vehicle_remove_evreview_name_remove_evreview_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_percentage',
            field=models.CharField(choices=[('10', '10%'), ('20', '20%'), ('30', '30%'), ('40', '40%'), ('50', '50%'), ('60', '60%'), ('70', '70%'), ('80', '80%'), ('90', '90%'), ('100', '100%')], default='0', max_length=20),
        ),
    ]
