# Generated by Django 5.1.2 on 2024-10-30 08:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectroTrail', '0006_vehicle_vehicle_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='upload_to',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
